# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3afe6eebb0f4213ffa8d270c0ebdccdd8f7d01084bb6f6a0c5bda92f69a33ca94d146c14e0c47ad207d8e29b153f7970be2bfd57b3270ed18d36bcaa8ab06685

test:
  secret_key_base: bcfa515ec6e31895a91764dd227dc9ab115ec3b3a4c53e9c5a16fa2c4b5a0db9dd3f414bd9ef790e61532343a37844f9ff9fe5feb312772e5eb87e4bc487d880

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
